name: github-hosted-pipeline

on:
  push: 
    branches:
      - master
      - main
      - development
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: List of My Favourite Food
        run: echo "Rice, Amala, Afang, Efo-Riro."
        shell: bash
